# Generated by Django 5.1.5 on 2025-01-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catstate',
            old_name='session_key',
            new_name='user_id',
        ),
    ]
