# Generated by Django 5.1.5 on 2025-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_session_key_catstate_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
